<a href="https://colab.research.google.com/github/shahdevansh28/ML/blob/main/ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
datasets = pd.read_csv('sample_data/Data_for_Transformation.csv')
print("Data:\n",datasets)

X = datasets.iloc[:,:-1].values
Y = datasets.iloc[:,-1].values
#print(X)
#print(Y)

X_new = datasets.iloc[:,1:3].values
#print(X_new)


scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_new)
print(X_scaled)

std = StandardScaler()
X_std = std.fit_transform(X_new)
print(X_std)


Data:
     Country  Age  Salary Purchased
0    France   44   72000        No
1     Spain   27   48000       Yes
2   Germany   30   54000        No
3     Spain   38   61000        No
4   Germany   40   68000       Yes
5    France   35   58000       Yes
6     Spain   39   52000        No
7    France   48   79000       Yes
8   Germany   50   83000        No
9    France   37   67000       Yes
10    Spain   45   55000        No
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739 0.57142857]
 [0.34782609 0.28571429]
 [0.52173913 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]
 [0.7826087  0.2       ]]
[[ 0.68188156  0.79548755]
 [-1.81835082 -1.41513049]
 [-1.37713334 -0.86247598]
 [-0.2005534  -0.21771238]
 [ 0.09359159  0.42705121]
 [-0.64177088 -0.49403964]
 [-0.05348091 -1.04669415]
 [ 1.27017153  1.44025115]
 [ 1.56431652  1.80868749]
 [-0.34762589  0.33494213]
 [ 0.82895405 -0.77036689]]

Steps for handling categorial data

In [ ]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

datasets = pd.read_csv('sample_data/Data_for_Categorical_Values.csv')
#print(datasets)
#print(datasets.describe())

X = datasets.iloc[:,0:3].values
Y = datasets.iloc[:,3].values
#print(X)
#print(Y)

le = LabelEncoder()
X[ : ,0] = le.fit_transform(X[ : ,0])
print(X)

#dummy = pd.get_dummies(datasets['Country'])
#print(dummy)
#datasets = datasets.drop(['Country','Purchased'],axis=1)
#print(datasets)
#datasets = pd.concat([dummy,datasets],axis=1)
#print(datasets)

onhotencoder = OneHotEncoder()
x = onhotencoder.fit_transform(datasets.Country.values.reshape(-1,1)).toarray()
print(x)


dfOneHot = 

[[0 44 72000]
 [2 27 48000]
 [1 30 54000]
 [2 38 61000]
 [1 40 68000]
 [0 35 58000]
 [2 39 52000]
 [0 48 79000]
 [1 50 83000]
 [0 37 67000]
 [2 45 55000]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
